### ISSUE TITLE
[🐛] Cannot find module 'queue-microtask'

### ISSUE THREAD

**Issue by JoshuaWalsh** [snyk/cli#1800]
- `node -v`: v15.14.0
- `npm -v`: 7.7.6
- `snyk -v`: "Error: Cannot find module 'queue-microtask'"
- OS: Windows 10
- Command run: `snyk protect`

### Expected behaviour
snyk protect should say "Successfully applied Snyk patches" and exit successfully

### Actual behaviour
snyk protect fails with this output:

```
Error: Cannot find module 'queue-microtask'
Require stack:
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\run-parallel\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.scandir\out\providers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.scandir\out\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.walk\out\readers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.walk\out\providers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.walk\out\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\fast-glob\out\readers\stream.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\fast-glob\out\providers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\fast-glob\out\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\globby\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\hashUtils.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\structUtils.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\formatUtils.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk-nodejs-lockfile-parser\dist\parsers\yarn2-lock-parser.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk-nodejs-lockfile-parser\dist\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-lock-parser.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\get-single-plugin-result.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\get-multi-plugin-result.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\get-deps-from-plugin.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\snyk-test\run-test.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\snyk-test\index.js
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\run-parallel\index.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
```

### Steps to reproduce
1. Clone ["feature/2021-04-update-dependencies" branch of jariz/gatsby-plugin-s3](https://github.com/jariz/gatsby-plugin-s3/tree/feature/2021-04-update-dependencies)
2. Run `npm i` in the root directory
3. Observe that snyk protect succeeds
4. `cd` to `examples/with-redirects`
5. Run `npm i`
6. Observe that snyk protect fails

**Comment by JackuB** [comment]
It seems like this https://github.com/jariz/gatsby-plugin-s3/commit/e13b687095cf026b745bd70567eb8870a54fd4d6 commit updated only `package.json` but not the `package-lock.json`.

Could you try running `npm i snyk@latest -S` to also update the package-lock?

**Comment by JoshuaWalsh** [comment]
I tried on a different computer and got the exact same result too.

**Comment by lili2311** [comment]
@JoshuaWalsh is this still an issue for you with latest version of CLI?

**Comment by lili2311** [comment]
@JoshuaWalsh closing this issue, please re-open if the issue persists and share some fresh reproducible info.

**Comment by JoshuaWalsh** [comment]
Hi @lili2311, sorry for my delay in replying. I have tested this and it appears to be resolved, thanks very much.

**Comment by JoshuaWalsh** [comment]
@lili2311 My previous message was mistaken, turns out I'd forgotten how to reproduce the issue. I just tested it again and I can confirm I'm still experiencing this problem.

`snyk -v` returns 1.657.0, this is also reflected in package-lock.json.

`snyk protect` fails by saying "Failed to get vulns". Here's the output of `snyk protect -d`:

```
PS D:\git\gatsby-plugin-s3\examples\with-redirects> snyk protect -d
  snyk protect <ref *1> { _: [ [Circular *1] ], debug: true } +0ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk Potential policy locations found: [rects project dir
  'D:\\git\\gatsby-plugin-s3\\examples\\with-redirects',
  'D:\\git\\gatsby-plugin-s3\\examples\\with-redirects\\node_modules\\snyk-docker-plugin',
  'D:\\git\\gatsby-plugin-s3\\examples\\with-redirects\\node_modules\\snyk-go-plugin',    
  'D:\\git\\gatsby-plugin-s3\\examples\\with-redirects\\node_modules\\gatsby-plugin-s3'   
] +0ms
  snyk:find-files Encountered multiple node lockfiles files, defaulting to D:\git\gatsby-plugin-s3\examples\with-redirects\package-lock.json +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm/patches +0ms
  snyk request body size: 150545951 +1ms      
  snyk gzipped request body size: 4863919 +0ms
  snyk not using proxy +1s
  snyk:run-test Error running test {..
  error: FailedToGetVulnerabilitiesError: Failed to get vulns
      at handleTestHttpErrorResponse (C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\lib\snyk-test\run-test.ts:510:13)
      at C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\lib\snyk-test\run-test.ts:477:21
      at requestWrapper (C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\lib\request\index.ts:27:7)
      at processTicksAndRejections (node:internal/process/task_queues:94:5) {
    code: 502,
    strCode: 'INTERNAL_SERVER_ERROR',
    innerError: undefined,
    userMessage: 'Failed to get vulns'
  }
} +0ms
FailedToRunTestError: Failed to get vulns
    at runTest (C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\lib\snyk-test\run-test.ts:363:11) 
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at patch (C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\cli\commands\protect\index.ts:87:23)
    at runCommand (C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\cli\index.ts:57:25)
    at main (C:\Users\josh\AppData\Roaming\nvm\v15.14.0\node_modules\snyk\src\cli\index.ts:313:11)

  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [
    {
      "debug": true
    }
  ],
  "command": "bad-command",
  "metadata": {
    "local": [
      true,
      true
    ],
    "generating-node-dependency-tree": {
      "lockFile": false,
      "targetFile": "package-lock.json"
    },
    "pluginName": "snyk-nodejs-lockfile-parser",
    "policies": 4,
    "policyLocations": [
      "D:\\git\\gatsby-plugin-s3\\examples\\with-redirects",
      "D:\\git\\gatsby-plugin-s3\\examples\\with-redirects\\node_modules\\snyk-docker-plugin",
      "D:\\git\\gatsby-plugin-s3\\examples\\with-redirects\\node_modules\\snyk-go-plugin",
      "D:\\git\\gatsby-plugin-s3\\examples\\with-redirects\\node_modules\\gatsby-plugin-s3"
    ],
    "packageManager": "npm",
    "packageName": "gatsby-starter-default",
    "packageVersion": "1.0.0",
    "package": "gatsby-starter-default@1.0.0",
    "payloadSize": 150545951,
    "gzippedPayloadSize": 4863919,
    "success": false,
    "error-message": "Failed to get vulns",
    "error": "FailedToRunTestError: Failed to get vulns\n    at runTest (C:\\Users\\josh\\AppData\\Roaming\\nvm\\v15.14.0\\node_modules\\snyk\\src\\lib\\snyk-test\\run-test.ts:363:11)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at patch (C:\\Users\\josh\\AppData\\Roaming\\nvm\\v15.14.0\\node_modules\\snyk\\src\\cli\\commands\\protect\\index.ts:87:23)\n    at runCommand (C:\\Users\\josh\\AppData\\Roaming\\nvm\\v15.14.0\\node_modules\\snyk\\src\\cli\\index.ts:57:25)\n    at main (C:\\Users\\josh\\AppData\\Roaming\\nvm\\v15.14.0\\node_modules\\snyk\\src\\cli\\index.ts:313:11)",
    "error-code": 502,
    "command": "protect"
  },
  "version": "1.657.0",
  "os": "Windows 10",
  "nodeVersion": "v15.14.0",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "c4631477dad4ead6942633a1868c06654f719bca",
  "ci": false,
  "environment": {
    "npmVersion": "7.7.6"
  },
  "durationMs": 105531,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [
        37806
      ],
      "total": 37806
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        67725
      ],
      "total": 67725
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +34s
  snyk request body size: 1893 +0ms
  snyk gzipped request body size: 780 +0ms
  snyk not using proxy +1ms
```

`npm i` fails with:

```
> snyk protect

Error: Cannot find module 'queue-microtask'
Require stack:
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\run-parallel\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.scandir\out\providers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.scandir\out\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.walk\out\readers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.walk\out\providers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@nodelib\fs.walk\out\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\fast-glob\out\readers\stream.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\fast-glob\out\providers\async.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\fast-glob\out\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\globby\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\hashUtils.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\structUtils.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\formatUtils.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\@yarnpkg\core\lib\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk-nodejs-lockfile-parser\dist\parsers\yarn2-lock-parser.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk-nodejs-lockfile-parser\dist\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-lock-parser.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\get-single-plugin-result.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\get-multi-plugin-result.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\plugins\get-deps-from-plugin.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\snyk-test\run-test.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\snyk-test\index.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\lib\analytics.js
- D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\snyk\dist\cli\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (D:\git\gatsby-plugin-s3\examples\with-redirects\node_modules\run-parallel\index.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR! code 1
npm ERR! path D:\git\gatsby-plugin-s3\examples\with-redirects
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run snyk-protect

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\josh\AppData\Local\npm-cache\_logs\2021-07-08T09_34_56_831Z-debug.log
```

**Comment by lili2311** [comment]
Are you able to share a reproducible project for us to test this with? If you prefer to keep it private you can email support@snyk.io and reference this issue so that the team can investigate 🙏

**Comment by JoshuaWalsh** [comment]
I'm encountering this issue on an open-source project so no problem there. The reproduction steps from my initial report include a link to the repository, and following them still reproduces the issue.

I'm wondering if the issue could be related to the fact that we have nested projects. Based on the `-d` output, `snyk` seems to detect this and use the correct lockfile, but this is the only thing I can think of that's unusual about our project.

Thanks very much for looking into this! This is causing some real problems for our CI pipeline.

**Comment by JackuB** [comment]
Snyk protect command will be removed from the Snyk CLI, see the announcement for more details: https://updates.snyk.io/snyk-wizard-and-snyk-protect-removal-224137
