### ISSUE TITLE
[🐛] npx snyk auth - unable to get local issuer certificate

### ISSUE THREAD

**Issue by pauly** [snyk/cli#2382]
- `node -v`: v14.17.6
- `npm -v`: 6.14.15
- `snyk -v`: 1.769.0
- OS: OSX just updated to Monterey
- Command run: npx snyk auth

### Expected behaviour

To be authenticated.

### Actual behaviour

`An unknown error occurred. Please run with `-d` and include full trace when reporting to Snyk`

The browser does open but I'm not authenticated in the terminal.

### Steps to reproduce

Please share _minimal_ steps needed to reproduce your issue. Ideally
a paired down manifest / project to showcase the problem that can also
be used for testing.

### Debug log

```
npx snyk auth -d
npx: installed 1 in 2.481s
  snyk auth { _: [], debug: true } +0ms
  snyk auth { _: [], debug: true } +0ms

Now redirecting you to our auth page, go ahead and log in,
and once the auth is complete, return to this prompt and you'll
be ready to start using snyk.

If you can't wait use this url:
https://snyk.io/login?token=64b32d80-snip-snip-snip-snipsnipsnip&utm_medium=cli&utm_source=cli&utm_campaign=cli&os=darwin&docker=false

  snyk not using proxy +0ms
| Waiting...  snyk sending request to: https://snyk.io/api/v1/verify/callback +75ms
  snyk request body size: 48 +0ms
  snyk gzipped request body size: 68 +0ms
  snyk not using proxy +0ms
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [],
  "command": "bad-command",
  "metadata": {
    "error-message": "unable to get local issuer certificate",
    "error": "Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:470:12)\n    at TLSSocket._finishInit (_tls_wrap.js:936:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)",
    "error-code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
    "command": "auth"
  },
  "os": "macOS Monterey",
  "version": "1.769.0",
  "nodeVersion": "v14.17.6",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "6f88174dc43723f9ade9df4a877bd5eabd498c16",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.15"
  },
  "durationMs": 1304,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [
        74,
        69
      ],
      "total": 143
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1161
      ],
      "total": 1161
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +668ms
  snyk request body size: 930 +0ms
  snyk gzipped request body size: 507 +0ms
  snyk not using proxy +1ms
  snyk analytics Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
} +55ms
```

**Comment by pauly** [comment]
I think on my local network one of the domains that is called here is blocked

**Comment by JackuB** [comment]
Please reach out to https://support.snyk.io/ for Snyk product questions, we are not able to support you in GitHub issues.

See https://docs.snyk.io/ for Snyk products documentation
