### ISSUE TITLE
[🐛] snyk python "ModuleNotFoundError: No module named 'setuptools"

### ISSUE THREAD

**Issue by gauravcanon** [snyk/cli#2772]
#Snyk command parameter not working as expected 

I am trying to run a python project snyk test. Working fine in IDE and Linux. But problem appearing in Teamcity CI/CD step

#### Not working if trying in TeamCity  CI/CD environment. 

```.bash
Build 'Multirepo_Buildpipleline / Build / Scan Vulnerabilities Repo 1' #59
Triggered 2022-02-19 15:27:27 by 'gauravdubey'
Started 2022-02-19 15:27:34 on agent 'teamcity-agent-2'
Finished 2022-02-19 15:27:46 with status FAILURE 'Failed to test pip project (Step: Snyk Security) (new); 0 known vulnerabilities | 0 dependencies (Step: Snyk Security) (new)'
VCS revisions: 'MultirepoBuildpipleline_Repo1' (Git, instance id 17): '1cb8f2ed76435691bbb813b28bf916c7b584e933' (branch: 'refs/heads/main')
TeamCity URL example.com/viewLog.html?buildId=2575&buildTypeId=MultirepoBuildpipleline_Build_ScanFor 
TeamCity server version is 2021.2.3 (build 99711), server timezone: GMT (UTC)

[15:27:28]E: bt28 (18s)
[15:27:28]i: TeamCity server version is 2021.2.3 (build 99711)
[15:27:28] : Collecting changes in 2 VCS roots (1s)
[15:27:28] :	 [Collecting changes in 2 VCS roots] VCS Root details
[15:27:28] :		 [VCS Root details] "Repo1" {instance id=17, parent internal id=18, parent id=MultirepoBuildpipleline_Repo1, description: "https://github.com/gauravcanon/repo1#main"}
[15:27:28] :		 [VCS Root details] "https://github.com/gauravcanon/repo1#refs/heads/main" {instance id=14, parent internal id=24, parent id=MultirepoBuildpipleline_Build_HttpsGithubComGauravcanonRepo1refsHeadsMain, description: "https://github.com/gauravcanon/repo1#refs/heads/main"}
[15:27:29]i:	 [Collecting changes in 2 VCS roots] Detecting changes in VCS root 'Repo1' (used in 'Scan Vulnerabilities Repo 1')
[15:27:29]i:	 [Collecting changes in 2 VCS roots] Will collect changes for 'Repo1' starting from revision 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:29]i:	 [Collecting changes in 2 VCS roots] Detecting changes in VCS root 'https://github.com/gauravcanon/repo1#refs/heads/main' (used in 'Build Repo 1')
[15:27:29]i:	 [Collecting changes in 2 VCS roots] Will collect changes for 'https://github.com/gauravcanon/repo1#refs/heads/main' starting from revision 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:29] :	 [Collecting changes in 2 VCS roots] Compute revision for 'Repo1'
[15:27:29] :		 [Compute revision for 'Repo1'] Upper limit revision: 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:29]i:		 [Compute revision for 'Repo1'] MaxModId = null
[15:27:29] :		 [Compute revision for 'Repo1'] The first revision that was detected in the branch refs/heads/main: 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:29] :		 [Compute revision for 'Repo1'] Cannot find modification in TeamCity database with revision 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:29] :		 [Compute revision for 'Repo1'] Verified that 1cb8f2ed76435691bbb813b28bf916c7b584e933 is the latest commit affecting the build
[15:27:29] :		 [Compute revision for 'Repo1'] Computed revision: 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:29] : The build is removed from the queue to be prepared for the start
[15:27:29] : Starting the build on the agent "teamcity-agent-2"
[15:27:34]i: Agent time zone: Europe/London
[15:27:34]i: Agent is running under JRE: 11.0.12+7-LTS
[15:27:34] : Updating tools for build
[15:27:34] :	 [Updating tools for build] Tools are not required for the build
[15:27:34] : Clearing temporary directory: /opt/buildagent/temp/buildTmp
[15:27:34] : Using vcs information from agent file: 6be8c4974ac55dba.xml
[15:27:34] : Checkout directory: /opt/buildagent/work/6be8c4974ac55dba
[15:27:34] : Updating sources: auto checkout (on agent) (1s)
[15:27:34] :	 [Updating sources] Will use agent side checkout
[15:27:34] :	 [Updating sources] VCS Root: Repo1 (1s)
[15:27:34] :		 [VCS Root: Repo1] revision: 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:34]i:		 [VCS Root: Repo1] Mirrors automatically enabled
[15:27:34] :		 [VCS Root: Repo1] Git version: 2.25.1.0
[15:27:34] :		 [VCS Root: Repo1] Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)
[15:27:34] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] /usr/bin/git config http.sslCAInfo
[15:27:34] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] /usr/bin/git show-ref
[15:27:34] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] /usr/bin/git -c core.askpass=/opt/buildagent/temp/buildTmp/pass9373696222917872834 -c credential.helper= ls-remote origin
[15:27:35] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] /usr/bin/git show-ref refs/heads/main
[15:27:35] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] /usr/bin/git log -n1 --pretty=format:%H%x20%s 1cb8f2ed76435691bbb813b28bf916c7b584e933 --
[15:27:35] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] No 'git fetch' required: commit '1cb8f2ed76435691bbb813b28bf916c7b584e933' is in the local repository clone pointed by 'refs/heads/main'.
[15:27:35] :			 [Update git mirror (/opt/buildagent/system/git/git-9ABAF406.git)] /usr/bin/git pack-refs --all
[15:27:35] :		 [VCS Root: Repo1] Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git rev-parse --is-shallow-repository
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git config lfs.storage /opt/buildagent/system/git/git-9ABAF406.git/lfs
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git config core.sparseCheckout true
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git config http.sslCAInfo
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git show-ref
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git show-ref refs/remotes/origin/main
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git log -n1 --pretty=format:%H%x20%s 1cb8f2ed76435691bbb813b28bf916c7b584e933 --
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] No 'git fetch' required: commit '1cb8f2ed76435691bbb813b28bf916c7b584e933' is in the local repository clone pointed by 'refs/remotes/origin/main'.
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git branch
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git -c core.askpass=/opt/buildagent/temp/buildTmp/pass3421560945336570743 -c credential.helper= -c credential.helper=/opt/buildagent/temp/buildTmp/credHelper7261229771874065815.sh reset --hard 1cb8f2ed76435691bbb813b28bf916c7b584e933
[15:27:35] :			 [Update checkout directory (/opt/buildagent/work/6be8c4974ac55dba)] /usr/bin/git branch --set-upstream-to=refs/remotes/origin/main
[15:27:35] : Build preparation done
[15:27:35]E: Step 1/1: Scan Vulnerabilities (Snyk Security) (1s)
[15:27:35] :	 [Step 1/1] Testing for known issues...
[15:27:35] :	 [Step 1/1] Starting: /opt/buildagent/tools/teamcity-snyk-security-plugin-runner/bin/1.770.0/snyk-linux test --json --severity-threshold=low --file=requirements.txt --command=/usr/bin/python3 --debug --skip-unresolved=true
[15:27:35] :	 [Step 1/1] in directory: /opt/buildagent/work/6be8c4974ac55dba
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.025Z snyk test <ref *1> {
[15:27:36]W:	 [Step 1/1]   _: [ [Circular *1] ],
[15:27:36]W:	 [Step 1/1]   json: true,
[15:27:36]W:	 [Step 1/1]   file: 'requirements.txt',
[15:27:36]W:	 [Step 1/1]   command: '/usr/bin/python3',
[15:27:36]W:	 [Step 1/1]   debug: true,
[15:27:36]W:	 [Step 1/1]   severityThreshold: 'low',
[15:27:36]W:	 [Step 1/1]   skipUnresolved: 'true',
[15:27:36]W:	 [Step 1/1]   allowMissing: true
[15:27:36]W:	 [Step 1/1] }
[15:27:36] :	 [Step 1/1] Publishing 1 file using [WebPublisher]
[15:27:36] :	 [Step 1/1] Publishing 1 file using [ArtifactsCachePublisher]
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.647Z snyk:run-test Error running test {
[15:27:36]W:	 [Step 1/1]   error: 'Traceback (most recent call last):\n' +
[15:27:36]W:	 [Step 1/1]     '  File "/opt/buildagent/temp/buildTmp/tmp-9456-w5p6xLDrFOKn/pip_resolve.py", line 10, in <module>\n' +
[15:27:36]W:	 [Step 1/1]     '    import setup_file\n' +
[15:27:36]W:	 [Step 1/1]     '  File "/opt/buildagent/temp/buildTmp/tmp-9456-w5p6xLDrFOKn/setup_file.py", line 3, in <module>\n' +
[15:27:36]W:	 [Step 1/1]     '    import setuptools\n' +
[15:27:36]W:	 [Step 1/1]     "ModuleNotFoundError: No module named 'setuptools'\n"
[15:27:36]W:	 [Step 1/1] }
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.751Z snyk analytics {
[15:27:36]W:	 [Step 1/1]   "args": [
[15:27:36]W:	 [Step 1/1]     {
[15:27:36]W:	 [Step 1/1]       "json": true,
[15:27:36]W:	 [Step 1/1]       "file": "requirements.txt",
[15:27:36]W:	 [Step 1/1]       "command": "/usr/bin/python3",
[15:27:36]W:	 [Step 1/1]       "debug": true,
[15:27:36]W:	 [Step 1/1]       "severityThreshold": "low",
[15:27:36]W:	 [Step 1/1]       "skipUnresolved": "true",
[15:27:36]W:	 [Step 1/1]       "allowMissing": true
[15:27:36]W:	 [Step 1/1]     }
[15:27:36]W:	 [Step 1/1]   ],
[15:27:36]W:	 [Step 1/1]   "command": "bad-command",
[15:27:36]W:	 [Step 1/1]   "metadata": {
[15:27:36]W:	 [Step 1/1]     "upgradable-snyk-protect-paths": 0,
[15:27:36]W:	 [Step 1/1]     "local": true,
[15:27:36]W:	 [Step 1/1]     "error-message": "{\n  \"ok\": false,\n  \"error\": \"Failed to test pip project\",\n  \"path\": \"/opt/buildagent/work/6be8c4974ac55dba\"\n}",
[15:27:36]W:	 [Step 1/1]     "error": "Error: {\n  \"ok\": false,\n  \"error\": \"Failed to test pip project\",\n  \"path\": \"/opt/buildagent/work/6be8c4974ac55dba\"\n}\n    at test (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:182:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at runCommand (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:53:25)\n    at main (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:317:11)\n    at /snapshot/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3\n    at Object.callHandlingUnexpectedErrors (/snapshot/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)",
[15:27:36]W:	 [Step 1/1]     "error-code": 500,
[15:27:36]W:	 [Step 1/1]     "command": "test"
[15:27:36]W:	 [Step 1/1]   },
[15:27:36]W:	 [Step 1/1]   "os": "Linux 5.10",
[15:27:36]W:	 [Step 1/1]   "osPlatform": "linux",
[15:27:36]W:	 [Step 1/1]   "osRelease": "5.10.60.1-microsoft-standard-WSL2",
[15:27:36]W:	 [Step 1/1]   "osArch": "x64",
[15:27:36]W:	 [Step 1/1]   "version": "1.855.0",
[15:27:36]W:	 [Step 1/1]   "nodeVersion": "v16.13.2",
[15:27:36]W:	 [Step 1/1]   "standalone": true,
[15:27:36]W:	 [Step 1/1]   "integrationName": "",
[15:27:36]W:	 [Step 1/1]   "integrationVersion": "",
[15:27:36]W:	 [Step 1/1]   "integrationEnvironment": "",
[15:27:36]W:	 [Step 1/1]   "integrationEnvironmentVersion": "",
[15:27:36]W:	 [Step 1/1]   "id": "32396b72cac05d1852f547a7990182e7dfc7a04c",
[15:27:36]W:	 [Step 1/1]   "ci": true,
[15:27:36]W:	 [Step 1/1]   "durationMs": 716,
[15:27:36]W:	 [Step 1/1]   "metrics": {
[15:27:36]W:	 [Step 1/1]     "network_time": {
[15:27:36]W:	 [Step 1/1]       "type": "timer",
[15:27:36]W:	 [Step 1/1]       "values": [],
[15:27:36]W:	 [Step 1/1]       "total": 0
[15:27:36]W:	 [Step 1/1]     },
[15:27:36]W:	 [Step 1/1]     "cpu_time": {
[15:27:36]W:	 [Step 1/1]       "type": "synthetic",
[15:27:36]W:	 [Step 1/1]       "values": [
[15:27:36]W:	 [Step 1/1]         716
[15:27:36]W:	 [Step 1/1]       ],
[15:27:36]W:	 [Step 1/1]       "total": 716
[15:27:36]W:	 [Step 1/1]     }
[15:27:36]W:	 [Step 1/1]   }
[15:27:36]W:	 [Step 1/1] }
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.752Z snyk sending request to: https://snyk.io/api/v1/analytics/cli
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.752Z snyk request body size: 1553
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.752Z snyk gzipped request body size: 727
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.752Z snyk not using proxy
[15:27:36]W:	 [Step 1/1] 2022-02-19T09:57:36.761Z snyk Exit code: 2
[15:27:37]W:	 [Step 1/1] Process exited with code 2
[15:27:37]E:	 [Step 1/1] Failed to test pip project (Step: Snyk Security)
[15:27:37]E:	 [Step 1/1] 0 known vulnerabilities | 0 dependencies (Step: Snyk Security)
[15:27:37] :	 [Step 1/1] Generating Snyk html report...
[15:27:37] :	 [Step 1/1] Starting: /opt/buildagent/tools/teamcity-snyk-security-plugin-runner/bin/1.770.0/snyk-to-html-linux -i /opt/buildagent/temp/buildTmp/snyk_report.json -o /opt/buildagent/temp/buildTmp/snyk_report.html
[15:27:37] :	 [Step 1/1] in directory: /opt/buildagent/work/6be8c4974ac55dba
[15:27:37] :	 [Step 1/1] Process exited with code 0
[15:27:37] :	 [Step 1/1] Publishing artifacts
[15:27:37] :		 [Publishing artifacts] Collecting files to publish: [/opt/buildagent/temp/buildTmp/snyk_report.html => .teamcity/snyk]
[15:27:37] :	 [Step 1/1] Publishing artifacts
[15:27:37] :		 [Publishing artifacts] Collecting files to publish: [/opt/buildagent/temp/buildTmp/snyk_report.json => .teamcity/snyk]
[15:27:37] :	 [Step 1/1] Publishing 1 file using [WebPublisher]: /opt/buildagent/temp/buildTmp/snyk_report.html => .teamcity/snyk
[15:27:37] :	 [Step 1/1] Publishing 1 file using [ArtifactsCachePublisher]: /opt/buildagent/temp/buildTmp/snyk_report.html => .teamcity/snyk
[15:27:37] :	 [Step 1/1] Publishing 1 file using [WebPublisher]: /opt/buildagent/temp/buildTmp/snyk_report.json => .teamcity/snyk
[15:27:37] :	 [Step 1/1] Publishing 1 file using [ArtifactsCachePublisher]: /opt/buildagent/temp/buildTmp/snyk_report.json => .teamcity/snyk
[15:27:37]E:	 [Step 1/1] Step Scan Vulnerabilities (Snyk Security) failed
[15:27:41] : Publishing 1 file using [WebPublisher]
[15:27:41] : Publishing 1 file using [ArtifactsCachePublisher]
[15:27:46] : Build finished


```

#### Tried running on Ubuntu 20.8 working fine . 
`snyk test --skip-unresolved=true`

```bash
Testing /mnt/c/Users/gaura/Documents/GitHub/GTCRM-backend...

Tested 44 dependencies for known issues, found 2 issues, 2 vulnerable paths.


Issues to fix by upgrading dependencies:

  Pin pip@20.0.2 to pip@21.1 to fix
  ✗ Improper Input Validation [Medium Severity][https://snyk.io/vuln/SNYK-PYTHON-PIP-1278135] in pip@20.0.2
    introduced by pipupgrade@1.12.0 > pip@20.0.2


Issues with no direct upgrade or patch:
  ✗ Out-of-Bounds Write [High Severity][https://snyk.io/vuln/SNYK-PYTHON-UJSON-2359034] in ujson@4.3.0
    introduced by ujson@4.3.0
  No upgrade or patch available



Organization:     org
Package manager:   pip
Target file:       requirements.txt
Project name:      GTCRM-backend
Open source:       no
Project path:      /mnt/c/Users/gaura/Documents/GitHub/GTCRM-backend
Licenses:          enabled

Tip: Try `snyk fix` to address these issues.`snyk fix` is a new CLI command in that aims to automatically apply the recommended updates for supported ecosystems.
See documentation on how to enable this beta feature: https://docs.snyk.io/features/snyk-cli/fix-vulnerabilities-from-the-cli/automatic-remediation-with-snyk-fix
```
_The above is working fine. Because python is found_

**Comment by gauravcanon** [comment]
I thought of creating `.venv` and working on that but it seems Snyk as TeamCity plugin doesn't have that option . 
I don't have any option to install pip or upgrade `setuptools` or work as` .venv` . any idea how this can be fixed . 

even TeamCity plugin is broken which is mentioned here https://github.com/snyk/teamcity-snyk-security-plugin/issues/49
We are already implemented this for all other workflows. this is needed for python workflow which is only working in local environment 


Possible workaround

- Don't use Snyk plugin and work in docker image. problem won't report . need manual script to work like this

**Comment by JackuB** [comment]
Closing as it's not relevant to the Snyk CLI. See https://docs.snyk.io for Snyk products documentation
Please reach out to https://support.snyk.io for Snyk product questions.
