### ISSUE TITLE
Can't detect supported target files on Azure DevOps pipeline agent

### ISSUE THREAD

**Issue by henry-swapglobal** [snyk/cli#3852]
Hey Snyk Team,

As part of my CI/CD, I'm trying to run `snyk test`. This is for a python project that using poetry. 

## This works just fine locally:
```
(.venv) ➜  client-portal git:(feature/app-dependency-scan) snyk test -d
  snyk test <ref *1> { _: [ [Circular *1] ], debug: true } +0ms
  snyk Potential policy locations found: [ '/Users/henry/PycharmProjects/client-portal' ] +0ms
  snyk:find-files File does not seem to exist, skipping:  mysql.sock +0ms
  snyk:find-files Encountered multiple node lockfiles files, defaulting to /Users/henry/PycharmProjects/client-portal/cdk/yarn.lock +68ms
  snyk:find-files Filtered out 1/3 files: /Users/henry/PycharmProjects/client-portal/cdk/package.json +4ms
  snyk:prune rootPkg { name: 'Client Portal', version: '0.1.0' } +0ms
  snyk:prune prePrunePathsCount: 107 +0ms
  snyk:prune isDenseGraph false +1ms
  snyk sending request to: https://api.snyk.io/v1/test-dep-graph +0ms
  snyk request body size: 9130 +0ms
  snyk gzipped request body size: 2088 +0ms
  snyk not using proxy +1ms

Testing /Users/henry/PycharmProjects/client-portal...

Organization:      henry-c5h
Package manager:   poetry
Target file:       pyproject.toml
Project name:      Client Portal
Open source:       no
Project path:      /Users/henry/PycharmProjects/client-portal
Local Snyk policy: found
Licenses:          enabled

✔ Tested 52 dependencies for known issues, no vulnerable paths found.
```

However if I try to run the same command as part of an azure dev ops pipeline, it can't find the target file. 
## Here's the yaml step within my pipeline:
```
- script: |
      yarn global add snyk
      ls  <-- I've added this to prove I am in the correct directory
      snyk test -d
    env:
      SNYK_TOKEN: $(SnykToken)
    displayName: 🕵 Application Security Scan
```

## Running on Azure DevOps:
```
Starting: 🕵 Application Security Scan
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/5964fc4e-93cf-4325-b047-a76390a02a6a.sh
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
success Installed "snyk@1.1006.0" with binaries:
      - snyk
Done in 1.64s.
Dockerfile
Makefile
README.md
cdk
docker-compose.ci.yaml
docker-compose.override.yaml
docker-compose.yaml
example.env
migrations
poetry.toml
pyproject.toml
scripts
src
tests
2022-09-15T23:57:15.168Z snyk test <ref *1> { _: [ [Circular *1] ], debug: true }
2022-09-15T23:57:16.159Z snyk-test Failed to test 1 projects, errors:
2022-09-15T23:57:16.687Z snyk-test error: Error: Could not detect supported target files in /home/vsts/work/1/s.
Please see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.
    at Object.formatTestError (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/format-test-error.ts:16:21)
    at test (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:131:13)
    at runCommand (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
    at main (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11)
    at /home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3
    at Object.callHandlingUnexpectedErrors (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)
Error: 
Testing /home/vsts/work/1/s...

Could not detect supported target files in /home/vsts/work/1/s.
Please see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.
    at test (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:258:19)
    at runCommand (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
    at main (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11)
    at /home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3
    at Object.callHandlingUnexpectedErrors (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)
2022-09-15T23:57:16.692Z snyk analytics {
  "args": [
    {
      "debug": true
    }
  ],
  "command": "bad-command",
  "metadata": {
    "upgradable-snyk-protect-paths": 0,
    "error-message": "\nTesting /home/vsts/work/1/s...\n\nCould not detect supported target files in /home/vsts/work/1/s.\nPlease see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.",
    "error": "Error: \nTesting /home/vsts/work/1/s...\n\nCould not detect supported target files in /home/vsts/work/1/s.\nPlease see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.\n    at test (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:258:19)\n    at runCommand (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)\n    at main (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11)\n    at /home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3\n    at Object.callHandlingUnexpectedErrors (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)",
    "command": "test"
  },
  "os": "Linux 5.15",
  "osPlatform": "linux",
  "osRelease": "5.15.0-1019-azure",
  "osArch": "x64",
  "version": "1.1006.0",
  "nodeVersion": "v16.17.0",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "7d062c95ba77677e226677f77df111db66c89eb3",
  "ci": true,
  "durationMs": 1488,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1488
      ],
      "total": 1488
    }
  }
}
2022-09-15T23:57:16.696Z snyk sending request to: https://api.snyk.io/v1/analytics/cli
2022-09-15T23:57:16.696Z snyk request body size: 1702
2022-09-15T23:57:16.696Z snyk gzipped request body size: 673
2022-09-15T23:57:16.698Z snyk not using proxy
2022-09-15T23:57:16.712Z snyk Exit code: 3
##[error]Bash exited with code '3'.
Finishing: 🕵 Application Security Scan
```

If I manually specify what file and package manager I'm using via `snyk test -d --file=pyproject.toml --package-manager=poetry` I get what looks like a parsing error on the first line of my `pyproject.toml`

## Running on Azure DevOps w/ --file and --package-manager:
```
2022-09-15T23:20:14.7533561Z ##[section]Starting: 🕵 Application Security Scan
2022-09-15T23:20:14.7545176Z ==============================================================================
2022-09-15T23:20:14.7545464Z Task         : Command line
2022-09-15T23:20:14.7545732Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-09-15T23:20:14.7545995Z Version      : 2.201.1
2022-09-15T23:20:14.7546175Z Author       : Microsoft Corporation
2022-09-15T23:20:14.7546453Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-09-15T23:20:14.7546816Z ==============================================================================
2022-09-15T23:20:14.8993144Z Generating script.
2022-09-15T23:20:14.9002318Z ========================== Starting Command Output ===========================
2022-09-15T23:20:14.9025976Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/64bb46bc-f4e4-407b-ac15-bfc4a42a7493.sh
2022-09-15T23:20:15.4030146Z yarn global v1.22.19
2022-09-15T23:20:15.4572001Z [1/4] Resolving packages...
2022-09-15T23:20:15.6942800Z [2/4] Fetching packages...
2022-09-15T23:20:16.8283449Z [3/4] Linking dependencies...
2022-09-15T23:20:16.8311909Z warning Workspaces can only be enabled in private projects.
2022-09-15T23:20:17.0803410Z [4/4] Building fresh packages...
2022-09-15T23:20:17.0866523Z success Installed "snyk@1.1006.0" with binaries:
2022-09-15T23:20:17.0869160Z       - snyk
2022-09-15T23:20:17.0884698Z Done in 1.70s.
2022-09-15T23:20:17.1034094Z Dockerfile
2022-09-15T23:20:17.1034798Z Makefile
2022-09-15T23:20:17.1035310Z README.md
2022-09-15T23:20:17.1035823Z cdk
2022-09-15T23:20:17.1037231Z docker-compose.ci.yaml
2022-09-15T23:20:17.1039619Z docker-compose.override.yaml
2022-09-15T23:20:17.1040197Z docker-compose.yaml
2022-09-15T23:20:17.1040545Z example.env
2022-09-15T23:20:17.1040864Z migrations
2022-09-15T23:20:17.1041152Z poetry.toml
2022-09-15T23:20:17.1041556Z pyproject.toml
2022-09-15T23:20:17.1041951Z scripts
2022-09-15T23:20:17.1042329Z src
2022-09-15T23:20:17.1042512Z tests
2022-09-15T23:20:17.2308281Z 2022-09-15T23:20:17.228Z snyk test <ref *1> {
2022-09-15T23:20:17.2311978Z   _: [ [Circular *1] ],
2022-09-15T23:20:17.2312570Z   debug: true,
2022-09-15T23:20:17.2313349Z   file: 'pyproject.toml',
2022-09-15T23:20:17.2314110Z   packageManager: 'poetry'
2022-09-15T23:20:17.2314613Z }
2022-09-15T23:20:18.9565886Z 2022-09-15T23:20:18.955Z snyk:run-test Error running test {
2022-09-15T23:20:18.9567400Z   error: "/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!\n" +
2022-09-15T23:20:18.9568928Z     `  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "\n` +
2022-09-15T23:20:18.9570411Z     'Traceback (most recent call last):\n' +
2022-09-15T23:20:18.9571587Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__\n' +
2022-09-15T23:20:18.9572772Z     '    req = REQUIREMENT.parseString(requirement_string)\n' +
2022-09-15T23:20:18.9574467Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString\n' +
2022-09-15T23:20:18.9575268Z     '    raise exc\n' +
2022-09-15T23:20:18.9576654Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString\n' +
2022-09-15T23:20:18.9578518Z     '    loc, tokens = self._parse( instring, 0 )\n' +
2022-09-15T23:20:18.9580268Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache\n' +
2022-09-15T23:20:18.9581634Z     '    loc,tokens = self.parseImpl( instring, preloc, doActions )\n' +
2022-09-15T23:20:18.9583588Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl\n' +
2022-09-15T23:20:18.9584534Z     '    loc, exprtokens = e._parse( instring, loc, doActions )\n' +
2022-09-15T23:20:18.9585389Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache\n' +
2022-09-15T23:20:18.9586857Z     '    loc,tokens = self.parseImpl( instring, preloc, doActions )\n' +
2022-09-15T23:20:18.9588115Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl\n' +
2022-09-15T23:20:18.9589010Z     '    return self.expr._parse( instring, loc, doActions, callPreParse=False )\n' +
2022-09-15T23:20:18.9590491Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache\n' +
2022-09-15T23:20:18.9592118Z     '    loc,tokens = self.parseImpl( instring, preloc, doActions )\n' +
2022-09-15T23:20:18.9592984Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl\n' +
2022-09-15T23:20:18.9594150Z     '    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )\n' +
2022-09-15T23:20:18.9594988Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache\n' +
2022-09-15T23:20:18.9595794Z     '    loc,tokens = self.parseImpl( instring, preloc, doActions )\n' +
2022-09-15T23:20:18.9596559Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl\n' +
2022-09-15T23:20:18.9597371Z     '    raise ParseException(instring, loc, self.errmsg, self)\n' +
2022-09-15T23:20:18.9598354Z     'pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)\n' +
2022-09-15T23:20:18.9599248Z     '\n' +
2022-09-15T23:20:18.9600361Z     'During handling of the above exception, another exception occurred:\n' +
2022-09-15T23:20:18.9600991Z     '\n' +
2022-09-15T23:20:18.9601770Z     'Traceback (most recent call last):\n' +
2022-09-15T23:20:18.9602705Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3103, in __init__\n' +
2022-09-15T23:20:18.9603632Z     '    super(Requirement, self).__init__(requirement_string)\n' +
2022-09-15T23:20:18.9604451Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__\n' +
2022-09-15T23:20:18.9605131Z     '    raise InvalidRequirement(\n' +
2022-09-15T23:20:18.9605895Z     `pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'[tool.po'"\n` +
2022-09-15T23:20:18.9606742Z     '\n' +
2022-09-15T23:20:18.9607404Z     'During handling of the above exception, another exception occurred:\n' +
2022-09-15T23:20:18.9608013Z     '\n' +
2022-09-15T23:20:18.9608598Z     'Traceback (most recent call last):\n' +
2022-09-15T23:20:18.9609518Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/pip_resolve.py", line 351, in <module>\n' +
2022-09-15T23:20:18.9610719Z     '    sys.exit(main())\n' +
2022-09-15T23:20:18.9613907Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/pip_resolve.py", line 342, in main\n' +
2022-09-15T23:20:18.9614464Z     '    create_dependencies_tree_by_req_file_path(\n' +
2022-09-15T23:20:18.9615095Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/pip_resolve.py", line 285, in create_dependencies_tree_by_req_file_path\n' +
2022-09-15T23:20:18.9615920Z     '    required = get_requirements_list(requirements_file_path, dev_deps=dev_deps)\n' +
2022-09-15T23:20:18.9616517Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/pip_resolve.py", line 252, in get_requirements_list\n' +
2022-09-15T23:20:18.9617040Z     '    req_list = list(requirements.parse(f))\n' +
2022-09-15T23:20:18.9617555Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/requirements/parser.py", line 78, in parse\n' +
2022-09-15T23:20:18.9618304Z     '    req = Requirement.parse(line)\n' +
2022-09-15T23:20:18.9618845Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/requirements/requirement.py", line 240, in parse\n' +
2022-09-15T23:20:18.9619502Z     '    return cls.parse_line(line)\n' +
2022-09-15T23:20:18.9620520Z     '  File "/tmp/tmp-1719-pTdkAQ8epKGf/requirements/requirement.py", line 218, in parse_line\n' +
2022-09-15T23:20:18.9621219Z     '    pkg_req = Req.parse(line)\n' +
2022-09-15T23:20:18.9622012Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3150, in parse\n' +
2022-09-15T23:20:18.9622553Z     '    req, = parse_requirements(s)\n' +
2022-09-15T23:20:18.9623549Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3096, in parse_requirements\n' +
2022-09-15T23:20:18.9624065Z     '    yield Requirement(line)\n' +
2022-09-15T23:20:18.9624757Z     '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3105, in __init__\n' +
2022-09-15T23:20:18.9625282Z     '    raise RequirementParseError(str(e))\n' +
2022-09-15T23:20:18.9625804Z     `pkg_resources.RequirementParseError: Invalid requirement, parse error at "'[tool.po'"\n`
2022-09-15T23:20:18.9626125Z }
2022-09-15T23:20:18.9626556Z 2022-09-15T23:20:18.957Z snyk-test Failed to test 1 projects, errors:
2022-09-15T23:20:19.5598417Z 2022-09-15T23:20:19.559Z snyk-test error: FailedToRunTestError: Failed to test poetry project
2022-09-15T23:20:19.5599972Z     at runTest (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/snyk-test/run-test.ts:313:11)
2022-09-15T23:20:19.5600992Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-09-15T23:20:19.5601674Z     at test (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:127:13)
2022-09-15T23:20:19.5602576Z     at runCommand (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
2022-09-15T23:20:19.5603330Z     at main (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11)
2022-09-15T23:20:19.5604251Z     at /home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3
2022-09-15T23:20:19.5605355Z     at Object.callHandlingUnexpectedErrors (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)
2022-09-15T23:20:19.5609107Z Error: 
2022-09-15T23:20:19.5609647Z Testing /home/vsts/work/1/s...
2022-09-15T23:20:19.5610121Z 
2022-09-15T23:20:19.5610554Z Failed to test poetry project
2022-09-15T23:20:19.5611162Z     at test (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:258:19)
2022-09-15T23:20:19.5611850Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-09-15T23:20:19.5612960Z     at runCommand (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
2022-09-15T23:20:19.5613868Z     at main (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11)
2022-09-15T23:20:19.5614590Z     at /home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3
2022-09-15T23:20:19.5615708Z     at Object.callHandlingUnexpectedErrors (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)
2022-09-15T23:20:19.5641508Z 2022-09-15T23:20:19.563Z snyk analytics {
2022-09-15T23:20:19.5642113Z   "args": [
2022-09-15T23:20:19.5642514Z     {
2022-09-15T23:20:19.5642884Z       "debug": true,
2022-09-15T23:20:19.5643303Z       "file": "pyproject.toml",
2022-09-15T23:20:19.5643722Z       "packageManager": "poetry"
2022-09-15T23:20:19.5644118Z     }
2022-09-15T23:20:19.5644459Z   ],
2022-09-15T23:20:19.5645037Z   "command": "bad-command",
2022-09-15T23:20:19.5645512Z   "metadata": {
2022-09-15T23:20:19.5646121Z     "upgradable-snyk-protect-paths": 0,
2022-09-15T23:20:19.5648010Z     "local": true,
2022-09-15T23:20:19.5648849Z     "error-message": "\nTesting /home/vsts/work/1/s...\n\nFailed to test poetry project",
2022-09-15T23:20:19.5651544Z     "error": "Error: \nTesting /home/vsts/work/1/s...\n\nFailed to test poetry project\n    at test (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:258:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at runCommand (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)\n    at main (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11)\n    at /home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3\n    at Object.callHandlingUnexpectedErrors (/home/vsts/.config/yarn/global/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)",
2022-09-15T23:20:19.5653891Z     "error-code": 500,
2022-09-15T23:20:19.5655147Z     "command": "test"
2022-09-15T23:20:19.5656389Z   },
2022-09-15T23:20:19.5656767Z   "os": "Linux 5.15",
2022-09-15T23:20:19.5657090Z   "osPlatform": "linux",
2022-09-15T23:20:19.5658418Z   "osRelease": "5.15.0-1019-azure",
2022-09-15T23:20:19.5658893Z   "osArch": "x64",
2022-09-15T23:20:19.5659241Z   "version": "1.1006.0",
2022-09-15T23:20:19.5659611Z   "nodeVersion": "v16.17.0",
2022-09-15T23:20:19.5659969Z   "standalone": false,
2022-09-15T23:20:19.5660324Z   "integrationName": "",
2022-09-15T23:20:19.5660700Z   "integrationVersion": "",
2022-09-15T23:20:19.5661061Z   "integrationEnvironment": "",
2022-09-15T23:20:19.5661624Z   "integrationEnvironmentVersion": "",
2022-09-15T23:20:19.5662018Z   "id": "e23ef272851c7abe23c87ccb3ea261d518b49aed",
2022-09-15T23:20:19.5662579Z   "ci": true,
2022-09-15T23:20:19.5663836Z   "durationMs": 2299,
2022-09-15T23:20:19.5664290Z   "metrics": {
2022-09-15T23:20:19.5664725Z     "network_time": {
2022-09-15T23:20:19.5665149Z       "type": "timer",
2022-09-15T23:20:19.5665603Z       "values": [],
2022-09-15T23:20:19.5666012Z       "total": 0
2022-09-15T23:20:19.5666417Z     },
2022-09-15T23:20:19.5667185Z     "cpu_time": {
2022-09-15T23:20:19.5667522Z       "type": "synthetic",
2022-09-15T23:20:19.5667868Z       "values": [
2022-09-15T23:20:19.5668178Z         2299
2022-09-15T23:20:19.5668657Z       ],
2022-09-15T23:20:19.5668956Z       "total": 2299
2022-09-15T23:20:19.5669272Z     }
2022-09-15T23:20:19.5669752Z   }
2022-09-15T23:20:19.5670031Z }
2022-09-15T23:20:19.5670848Z 2022-09-15T23:20:19.565Z snyk sending request to: https://api.snyk.io/v1/analytics/cli
2022-09-15T23:20:19.5671851Z 2022-09-15T23:20:19.565Z snyk request body size: 1509
2022-09-15T23:20:19.5672963Z 2022-09-15T23:20:19.565Z snyk gzipped request body size: 662
2022-09-15T23:20:19.5678100Z 2022-09-15T23:20:19.567Z snyk not using proxy
2022-09-15T23:20:19.5834495Z 2022-09-15T23:20:19.583Z snyk Exit code: 2
2022-09-15T23:20:19.8609416Z ##[error]Bash exited with code '2'.
2022-09-15T23:20:19.8659914Z ##[section]Finishing: 🕵 Application Security Scan
```

**Comment by jmabry** [comment]
This issue has affected our team as well. Trying to use the snyk GHA runner for python.
