### ISSUE TITLE
Unit tests require a snyk token

### ISSUE THREAD

**Issue by candrews** [snyk/cli#4200]
Quoting https://github.com/snyk/cli/blob/master/CONTRIBUTING.md
> Unit tests must be fast. They should not test services outside the code itself. Services include filesystems, processes and networks.

Some of the unit tests require a snyk token to be configured contrary to the documented requirement to not do so.

To reproduce this issue, from the directory which contains the snyk cli project source code:
```sh
rm ~/.config/configstore/snyk.json
unset SNYK_TOKEN
npm ci
npm run build:prod
npm run test:unit
```

The following unit tests fail when no snyk token is configured:
```
Summary of all failing tests
 FAIL  test/jest/unit/python/snyk-test-pyproject.spec.ts
  ● snyk test for python project › no flag is used › project contains pyproject.toml file › should scan poetry vulnerabilities

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.test [as default] (src/cli/commands/test/index.ts:54:28)
      at Object.<anonymous> (test/jest/unit/python/snyk-test-pyproject.spec.ts:58:52)

  ● snyk test for python project › --all-projects flag is used to scan the project › project does not contain poetry.lock file › should not attempt to scan poetry vulnerabilities

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.test [as default] (src/cli/commands/test/index.ts:54:28)
      at Object.<anonymous> (test/jest/unit/python/snyk-test-pyproject.spec.ts:131:52)

  ● snyk test for python project › --all-projects flag is used to scan the project › project does contain poetry.lock file › should scan poetry vulnerabilities

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.test [as default] (src/cli/commands/test/index.ts:54:28)
      at Object.<anonymous> (test/jest/unit/python/snyk-test-pyproject.spec.ts:215:52)

 FAIL  test/jest/unit/lib/commands/fix/fix.spec.ts
  ● snyk fix (functional tests) › shows successful fixes Python requirements.txt project was fixed via --file

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:53:21)

  ● snyk fix (functional tests) › shows successful fixes Python requirements.txt project on stdout

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:91:21)

  ● snyk fix (functional tests) › shows successful fixes Python custom name base.txt project was fixed via --file

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:131:21)

  ● snyk fix (functional tests) › snyk fix continues to fix when 1 path fails to test with `snyk fix path1 path2` (exit code 0)

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:178:21)

  ● snyk fix (functional tests) › snyk fix send errors as analytics when fix fails

    TypeError: Cannot read properties of undefined (reading '1')

      265 |
      266 |       expect(snykFixSpy).toHaveBeenCalledTimes(1);
    > 267 |       expect(stripAnsi(res)).toMatch('✔ Upgraded Jinja2 from 2.7.2 to 2.11.3');
          |                                        ^
      268 |       // only use ora to output
      269 |       expect(stdoutMessages).toEqual('');
      270 |       expect(stderrMessages).toEqual('');

      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:267:40)

  ● snyk fix (functional tests) › snyk fails to fix when all paths fails to test with `snyk fix path1 path2` (non 0 error code)

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 8
    Received number of calls: 0

      319 |         meta: {
      320 |           fixed: 0,
    > 321 |           failed: 1,
          |                                 ^
      322 |           fixableIssues: 14,
      323 |           fixedIssues: 0,
      324 |           totalIssues: 14,

      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:321:33)

  ● snyk fix (functional tests) › snyk succeeds to fix when no vulns `snyk fix path1` (exit code 0)

    MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.

      21 |   if (!configured) {
      22 |     throw new MissingApiTokenError();
    > 23 |   }
         |    ^
      24 |   return configured;
      25 | }
      26 |

      at Object.apiTokenExists (src/lib/api-token.ts:23:15)
      at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
      at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
      at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:354:21)
````

**Comment by Jimimaku** [comment]
> Zitathttps://github.com/snyk/cli/blob/master/CONTRIBUTING.md
> 
> > Komponententests müssen schnell durchgeführt werden. Sie sollten keine Dienste außerhalb des Codes selbst testen. Zu den Dienstleistungen gehören Dateisysteme, Prozesse und Netzwerke.
> 
> Einige der Komponententests erfordern, dass ein Snyk-Token konfiguriert wird, entgegen der dokumentierten Anforderung, dies nicht zu tun.
> 
> Um dieses Problem zu reproduzieren, aus dem Verzeichnis, das den Quellcode des snyk cli-Projekts enthält:
> 
> ```shell
> rm ~/.config/configstore/snyk.json
> unset SNYK_TOKEN
> npm ci
> npm run build:prod
> npm run test:unit
> ```
> 
> Die folgenden Komponententests schlagen fehl, wenn kein Snyk-Token konfiguriert ist:
> 
> ```
> Summary of all failing tests
>  FAIL  test/jest/unit/python/snyk-test-pyproject.spec.ts
>   ● snyk test for python project › no flag is used › project contains pyproject.toml file › should scan poetry vulnerabilities
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.test [as default] (src/cli/commands/test/index.ts:54:28)
>       at Object.<anonymous> (test/jest/unit/python/snyk-test-pyproject.spec.ts:58:52)
> 
>   ● snyk test for python project › --all-projects flag is used to scan the project › project does not contain poetry.lock file › should not attempt to scan poetry vulnerabilities
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.test [as default] (src/cli/commands/test/index.ts:54:28)
>       at Object.<anonymous> (test/jest/unit/python/snyk-test-pyproject.spec.ts:131:52)
> 
>   ● snyk test for python project › --all-projects flag is used to scan the project › project does contain poetry.lock file › should scan poetry vulnerabilities
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.test [as default] (src/cli/commands/test/index.ts:54:28)
>       at Object.<anonymous> (test/jest/unit/python/snyk-test-pyproject.spec.ts:215:52)
> 
>  FAIL  test/jest/unit/lib/commands/fix/fix.spec.ts
>   ● snyk fix (functional tests) › shows successful fixes Python requirements.txt project was fixed via --file
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:53:21)
> 
>   ● snyk fix (functional tests) › shows successful fixes Python requirements.txt project on stdout
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:91:21)
> 
>   ● snyk fix (functional tests) › shows successful fixes Python custom name base.txt project was fixed via --file
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:131:21)
> 
>   ● snyk fix (functional tests) › snyk fix continues to fix when 1 path fails to test with `snyk fix path1 path2` (exit code 0)
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:178:21)
> 
>   ● snyk fix (functional tests) › snyk fix send errors as analytics when fix fails
> 
>     TypeError: Cannot read properties of undefined (reading '1')
> 
>       265 |
>       266 |       expect(snykFixSpy).toHaveBeenCalledTimes(1);
>     > 267 |       expect(stripAnsi(res)).toMatch('✔ Upgraded Jinja2 from 2.7.2 to 2.11.3');
>           |                                        ^
>       268 |       // only use ora to output
>       269 |       expect(stdoutMessages).toEqual('');
>       270 |       expect(stderrMessages).toEqual('');
> 
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:267:40)
> 
>   ● snyk fix (functional tests) › snyk fails to fix when all paths fails to test with `snyk fix path1 path2` (non 0 error code)
> 
>     expect(jest.fn()).toHaveBeenCalledTimes(expected)
> 
>     Expected number of calls: 8
>     Received number of calls: 0
> 
>       319 |         meta: {
>       320 |           fixed: 0,
>     > 321 |           failed: 1,
>           |                                 ^
>       322 |           fixableIssues: 14,
>       323 |           fixedIssues: 0,
>       324 |           totalIssues: 14,
> 
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:321:33)
> 
>   ● snyk fix (functional tests) › snyk succeeds to fix when no vulns `snyk fix path1` (exit code 0)
> 
>     MissingApiTokenError: `snyk` requires an authenticated account. Please run `snyk auth` and try again.
> 
>       21 |   if (!configured) {
>       22 |     throw new MissingApiTokenError();
>     > 23 |   }
>          |    ^
>       24 |   return configured;
>       25 | }
>       26 |
> 
>       at Object.apiTokenExists (src/lib/api-token.ts:23:15)
>       at Object.validateCredentials (src/cli/commands/test/validate-credentials.ts:7:21)
>       at Object.fix [as default] (src/cli/commands/fix/index.ts:30:28)
>       at Object.<anonymous> (test/jest/unit/lib/commands/fix/fix.spec.ts:354:21)
> ```
