### ISSUE TITLE
Error Message Incorrect

### ISSUE THREAD

**Issue by danpetitt** [snyk/cli#4268]
This error message is incorrect and should be an interpolated string:
https://github.com/snyk/cli/blob/bbf6cc0d15d684b58a1cc0d452835b9027aaefea/src/lib/errors/unsupported-entitlement-error.ts#L12

```
super('Unsupported feature - Missing the ${entitlementName} entitlement');
```

Should be:
```
super(`Unsupported feature - Missing the ${entitlementName} entitlement`);
```

We are getting this message on a simple JSON file in VS Code with the Snyk Extension:
```
Snyk CLI error executing [/home/dan/.local/share/snyk-ls/snyk-linux iac test /home/dan/projects/tv-pawa-exports-samsung-rtl-library/assembly/attributes.json --json]. Output: UnsupportedEntitlementError: Unsupported feature - Missing the ${entitlementName} entitlement
    at Object.default_1 [as default] (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/iac/index.ts:32:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at test (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:71:14)
    at runCommand (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
    at main (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:294:11)
    at /snapshot/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3
    at Object.callHandlingUnexpectedErrors (/snapshot/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)



STDERR output:
: exit status 2
```

**Comment by GeorgeDavis-TriumphTech** [comment]
I keep seeing this message on VSCode extension (snyk-security.snyk-vulnerability-scanner) under the Problems panel on macOS. It fails for every file in the repo and makes it challenging to continue using the VSCode extension. I am looking to fix the issue or disable the extension altogether. Any help here is much appreciated.

**Comment by lili2311** [comment]
@danpetitt thats for raising the issue a fix is now merged & deploying

**Comment by GeorgeDavis-TriumphTech** [comment]
Thank you for your prompt response. The issue still seems to persist. Here is a copy of the error message and the version of my Snyk CLI.

```
Snyk CLI error executing [/Users/george/Library/Application Support/snyk-ls/snyk-macos iac test /Users/george/sam-java-11 --json]. Output: UnsupportedEntitlementError: Unsupported feature - Missing the ${entitlementName} entitlement
    at Object.default_1 [as default] (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/iac/index.ts:32:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at test (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:71:14)
    at runCommand (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
    at main (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:294:11)
    at /snapshot/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:13:3
    at Object.callHandlingUnexpectedErrors (/snapshot/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)

STDERR output:
: exit status 2
```

**Installed CLI version:**

```
george@Georges-MacBook-Pro snyk-ls % pwd
/Users/george/Library/Application Support/snyk-ls

george@Georges-MacBook-Pro snyk-ls % ls -alrt
total 184536
-rw-r--r--@  1 george  staff         0 27 Dec 21:18 .installed_event_sent
-rwxr-xr-x@  1 george  staff  76922208 17 Feb 08:45 snyk-macos
drwx------+ 46 george  staff      1472 17 Feb 08:45 ..
drwxr-xr-x@  5 george  staff       160 20 Feb 11:47 .
-rwxr--r--@  1 george  staff  10058578 20 Feb 11:47 snyk-ls_darwin_arm64

george@Georges-MacBook-Pro snyk-ls % ./snyk-macos version
1.1105.0
```

This is the same version I have on my Apple M1 machine, when installed with the Snyk extension for VSCode or from Homebrew.

**Comment by GeorgeDavis-TriumphTech** [comment]
The issue still persists and it is impairing the use of other extensions on VSCode. Having 3k+ under Problems is stopping me from identifying actual issues highlighted by other extensions. I will uninstall the extension for now until this issue can be fixed.

![Screenshot 2023-04-18 at 9 21 05 AM](https://user-images.githubusercontent.com/120606123/232841674-dbc51625-db3a-49ca-95cc-11da6613c8c6.jpg)

```
george@Georges-MBP ~ % cd "/Users/george/Library/Application Support/snyk-ls/snyk-macos"
cd: not a directory: /Users/george/Library/Application Support/snyk-ls/snyk-macos
george@Georges-MBP ~ % cd "/Users/george/Library/Application Support/snyk-ls/" 
george@Georges-MBP snyk-ls % ./snyk-macos -v
1.1142.0
```
