### ISSUE TITLE
Problem with latest version (1.1102.0) trying to install globally npm-cli-login

### ISSUE THREAD

**Issue by satz-pando** [snyk/cli#4454]
RUN NPM_USER=${NPM_USERNAME} NPM_PASS=${NPM_PASSWORD} NPM_EMAIL=${NPM_EMAIL} NPM_REGISTRY=${NPM_REGISTRY} npx npm-cli-login
 ---> Running in 810790b3c24b
[91minternal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/npm-cli-login/node_modules/snyk/wrapper_dist/bootstrap.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[0m[91mnpm ERR! code ELIFECYCLE
[0m[91mnpm ERR! errno 1
[0m[91mnpm ERR! snyk@1.1112.0 postinstall: `node wrapper_dist/bootstrap.js exec`
npm [0m[91mERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snyk@1.1112.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-06T10_32_55_825Z-debug.log
[0m[91mInstall for [ 'npm-cli-login@latest' ] failed with code 1
[0mThe command '/bin/sh -c NPM_USER=${NPM_USERNAME} NPM_PASS=${NPM_PASSWORD} NPM_EMAIL=${NPM_EMAIL} NPM_REGISTRY=${NPM_REGISTRY} npx npm-cli-login' returned a non-zero code: 1

**Comment by JoaoBGusmao** [comment]
I had to fork npm-cli-login and update it's package.json to use a snyk version from a couple days ago. In my case
```json
"snyk": "1.1109.0"
```
worked well.

Then I installed the version directly from my github before the step where the npm-cli-login is ran:
```
npm i -g https://github...../user/....
```
