### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'link')

### ISSUE THREAD

**Issue by dregimbal1** [snyk/cli#4483]
Without digging too deep into it this seems to stem possibly from this line... https://github.com/snyk/nodejs-lockfile-parser/commit/16aebd10693731eb5df2d5823f7eaac31f1406c5#diff-81f70fb04fd56113a23046eb84b767b2c22af26fb791de3e071b1ecce7170fceR198

>   // Check for workspaces
  if (**depData['link']** && resolvedToWorkspace()) {
    childNodeKey = depData.resolved as string;
    depData = pkgs[depData.resolved as string];
  }

>   snyk:run-test Error running test {
  **error: TypeError: Cannot read properties of undefined (reading 'link')**
      at getChildNode (C:\snapshot\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nodejs-lockfile-parser\dist\dep-graph-builders\npm-lock-v2\index.js:112:1)
      at dfsVisit (C:\snapshot\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nodejs-lockfile-parser\dist\dep-graph-builders\npm-lock-v2\index.js:61:1)
      at dfsVisit (C:\snapshot\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nodejs-lockfile-parser\dist\dep-graph-builders\npm-lock-v2\index.js:71:1)
      at dfsVisit (C:\snapshot\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nodejs-lockfile-parser\dist\dep-graph-builders\npm-lock-v2\index.js:71:1)
      at buildDepGraphNpmLockV2 (C:\snapshot\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nodejs-lockfile-parser\dist\dep-graph-builders\npm-lock-v2\index.js:54:1)
      at Object.parseNpmLockV2Project (C:\snapshot\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nodejs-lockfile-parser\dist\dep-graph-builders\npm-lock-v2\index.js:17:1)
      at buildDepGraph (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\plugins\nodejs-plugin\npm-lock-parser.ts:135:29)      at Object.parse (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\plugins\nodejs-plugin\npm-lock-parser.ts:67:18)
      at Object.inspect (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\plugins\nodejs-plugin\index.ts:30:24)
      at Object.inspect (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\module-info\index.ts:23:33)
      at Object.getSinglePluginResult (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\plugins\get-single-plugin-result.ts:14:64)
      at Object.getDepsFromPlugin (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\plugins\get-deps-from-plugin.ts:103:22)
      at assembleLocalPayloads (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\snyk-test\run-test.ts:572:24)
      at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)
      at Function.runMain (pkg/prelude/bootstrap.js:1984:13)
      at node:internal/main/run_main_module:17:47
      at runTest (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\snyk-test\run-test.ts:326:22)
      at test (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\cli\commands\test\index.ts:155:13)
      at runCommand (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\cli\main.ts:51:25)
      at main (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\cli\main.ts:294:11)
      at C:\snapshot\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:13:3
      at Object.callHandlingUnexpectedErrors (C:\snapshot\snyk\dist\cli\webpack:\snyk\src\lib\unexpected-error.ts:28:5)
} +0ms

**Comment by orsagie** [comment]
@dregimbal1 thanks for raising this. Do you have a project I can use to reproduce this?

**Comment by menocomp** [comment]
I have the same issue as well in 1.1124.0 and 1.1125.0 and 1.1126.0 (currently latest).
Not replicated in 1.1123.0.

**Comment by mkielar** [comment]
@orsagie I've provided a test case in Ticket 46377 on your Support System if you haven't heard from them yet. (I work for a Client who is a paying customer of yours). There's package.json, and package-lock.json generated by nodes 16.x. We also reproduce it on package-lock.json filesngenerated by v18.x. Hope this helps.

**Comment by dregimbal1** [comment]
This appears to be resolved in the latest version ([v1.1139.0](https://github.com/snyk/cli/releases/tag/v1.1139.0)) last I tried. Thanks!
