### ISSUE TITLE
Updating urllib3 to version 1.24.3 doesn't clear issue

### ISSUE THREAD

**Issue by bertdida** [snyk/cli#485]
- `node -v`: v10.15.3
- `npm -v`: 6.9.0
- `snyk -v`: 1.161.1
- Command run: snyk test

### Expected behaviour
No issues found

### Actual behaviour
```shell
DS@B3-3 MINGW64 ~/Desktop/test/TwitterQuoteScraper (master)
$ snyk test

Testing C:\Users\DS\Desktop\test\TwitterQuoteScraper...

✗ High severity vulnerability found in urllib3
  Description: CRLF injection
  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
  Introduced through: gspread@3.1.0, tweepy@3.7.0
  From: gspread@3.1.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests-oauthlib@1.2.0 > requests@2.21.0 > urllib3@1.24.3




Organisation:      bertdida
Package manager:   pip
Target file:       Pipfile
Open source:       no
Project path:      C:\Users\DS\Desktop\test\TwitterQuoteScraper

Tested 19 dependencies for known vulnerabilities, found 1 vulnerability, 3 vulnerable paths.
```

### Steps to reproduce
```shell
git clone https://github.com/bertdida/TwitterQuoteScraper.git
pipenv install
pipenv shell
snyk test
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```shell
DS@B3-3 MINGW64 ~/Desktop/test/TwitterQuoteScraper (master)
$ snyk test --debug
2019-05-07T07:32:48.514Z snyk test { _: [ [Circular] ], debug: true }
2019-05-07T07:32:48.544Z snyk no file specified. Trying to autodetect in base folder C:\Users\DS\Desktop\test\TwitterQuoteScraper
2019-05-07T07:32:48.545Z snyk found package file Pipfile in C:\Users\DS\Desktop\test\TwitterQuoteScraper
2019-05-07T07:32:48.546Z snyk analytics add local true
2019-05-07T07:32:48.548Z snyk found package file Pipfile in C:\Users\DS\Desktop\test\TwitterQuoteScraper
2019-05-07T07:32:48.551Z snyk calling plugin inspect() { root: 'C:\\Users\\DS\\Desktop\\test\\TwitterQuoteScraper',
  targetFile: 'Pipfile',
  pluginOptions:
   { args: undefined,
     _: [ [Object] ],
     debug: true,
     org: undefined,
     showVulnPaths: true,
     path: 'C:\\Users\\DS\\Desktop\\test\\TwitterQuoteScraper',
     packageManager: 'pip',
     file: 'Pipfile' } }
2019-05-07T07:32:50.411Z snyk plugin inspect() done
2019-05-07T07:32:50.412Z snyk converting dep-tree to dep-graph { name: 'TwitterQuoteScraper', targetFile: 'Pipfile' }
2019-05-07T07:32:50.420Z snyk done converting dep-tree to dep-graph { uniquePkgsCount: 20 }
2019-05-07T07:32:50.420Z snyk analytics add policies 1
2019-05-07T07:32:50.420Z snyk analytics add packageManager pip
2019-05-07T07:32:50.420Z snyk analytics add packageName TwitterQuoteScraper
2019-05-07T07:32:50.420Z snyk analytics add packageVersion 0.0.0
2019-05-07T07:32:50.420Z snyk analytics add package TwitterQuoteScraper@0.0.0
2019-05-07T07:32:50.426Z snyk sending request to: https://snyk.io/api/v1/test-dep-graph
2019-05-07T07:32:50.426Z snyk request body size: 3454
2019-05-07T07:32:50.426Z snyk gzipped request body size: 750
2019-05-07T07:32:50.426Z snyk analytics add payloadSize 3454
2019-05-07T07:32:50.426Z snyk analytics add gzippedPayloadSize 750
2019-05-07T07:32:50.427Z snyk not using proxy
2019-05-07T07:32:53.190Z snyk analytics add vulns-pre-policy 3
2019-05-07T07:32:53.198Z snyk analytics add vulns 3
2019-05-07T07:32:53.238Z snyk analytics add error-message
Testing C:\Users\DS\Desktop\test\TwitterQuoteScraper...

✗ High severity vulnerability found in urllib3
  Description: CRLF injection
  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
  Introduced through: gspread@3.1.0, tweepy@3.7.0
  From: gspread@3.1.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests-oauthlib@1.2.0 > requests@2.21.0 > urllib3@1.24.3




Organisation:      bertdida
Package manager:   pip
Target file:       Pipfile
Open source:       no
Project path:      C:\Users\DS\Desktop\test\TwitterQuoteScraper

Tested 19 dependencies for known vulnerabilities, found 1 vulnerability, 3 vulnerable paths.
2019-05-07T07:32:53.238Z snyk analytics add error Error:
Testing C:\Users\DS\Desktop\test\TwitterQuoteScraper...

✗ High severity vulnerability found in urllib3
  Description: CRLF injection
  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
  Introduced through: gspread@3.1.0, tweepy@3.7.0
  From: gspread@3.1.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests-oauthlib@1.2.0 > requests@2.21.0 > urllib3@1.24.3




Organisation:      bertdida
Package manager:   pip
Target file:       Pipfile
Open source:       no
Project path:      C:\Users\DS\Desktop\test\TwitterQuoteScraper

Tested 19 dependencies for known vulnerabilities, found 1 vulnerability, 3 vulnerable paths.
    at C:\Users\DS\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test.ts:160:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\DS\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-07T07:32:53.238Z snyk analytics add error-code undefined
2019-05-07T07:32:53.238Z snyk analytics add command test
Error:
Testing C:\Users\DS\Desktop\test\TwitterQuoteScraper...

✗ High severity vulnerability found in urllib3
  Description: CRLF injection
  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
  Introduced through: gspread@3.1.0, tweepy@3.7.0
  From: gspread@3.1.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests@2.21.0 > urllib3@1.24.3
  From: tweepy@3.7.0 > requests-oauthlib@1.2.0 > requests@2.21.0 > urllib3@1.24.3




Organisation:      bertdida
Package manager:   pip
Target file:       Pipfile
Open source:       no
Project path:      C:\Users\DS\Desktop\test\TwitterQuoteScraper

Tested 19 dependencies for known vulnerabilities, found 1 vulnerability, 3 vulnerable paths.
    at C:\Users\DS\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test.ts:160:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\DS\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-07T07:32:53.330Z snyk analytics { args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  command: 'bad-command',
  metadata:
   { local: true,
     policies: 1,
     packageManager: 'pip',
     packageName: 'TwitterQuoteScraper',
     packageVersion: '0.0.0',
     package: 'TwitterQuoteScraper@0.0.0',
     payloadSize: 3454,
     gzippedPayloadSize: 750,
     'vulns-pre-policy': 3,
     vulns: 3,
     'error-message':
      '\nTesting C:\\Users\\DS\\Desktop\\test\\TwitterQuoteScraper...\n\n✗ High severity vulnerability found in urllib3\n  Description: CRLF injection\n  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323\n  Introduced through: gspread@3.1.0, tweepy@3.7.0\n  From: gspread@3.1.0 > requests@2.21.0 > urllib3@1.24.3\n  From: tweepy@3.7.0 > requests@2.21.0 > urllib3@1.24.3\n  From: tweepy@3.7.0 > requests-oauthlib@1.2.0 > requests@2.21.0 > urllib3@1.24.3\n\n\n\n\nOrganisation:      bertdida\nPackage manager:   pip\nTarget file:       Pipfile\nOpen source:       no\nProject path:      C:\\Users\\DS\\Desktop\\test\\TwitterQuoteScraper\n\nTested 19 dependencies for known vulnerabilities, found 1 vulnerability, 3 vulnerable paths.',
     error:
      'Error: \nTesting C:\\Users\\DS\\Desktop\\test\\TwitterQuoteScraper...\n\n✗ High severity vulnerability found in urllib3\n  Description: CRLF injection\n  Info: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323\n  Introduced through: gspread@3.1.0, tweepy@3.7.0\n  From: gspread@3.1.0 > requests@2.21.0 > urllib3@1.24.3\n  From: tweepy@3.7.0 > requests@2.21.0 > urllib3@1.24.3\n  From: tweepy@3.7.0 > requests-oauthlib@1.2.0 > requests@2.21.0 > urllib3@1.24.3\n\n\n\n\nOrganisation:      bertdida\nPackage manager:   pip\nTarget file:       Pipfile\nOpen source:       no\nProject path:      C:\\Users\\DS\\Desktop\\test\\TwitterQuoteScraper\n\nTested 19 dependencies for known vulnerabilities, found 1 vulnerability, 3 vulnerable paths.\n    at C:\\Users\\DS\\AppData\\Roaming\\npm\\node_modules\\snyk\\src\\cli\\commands\\test.ts:160:19\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\DS\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\commands\\test.js:4:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': undefined,
     command: 'test' },
  version: '1.161.1',
  os: 'Windows 10',
  nodeVersion: 'v10.15.3',
  id: 'cec74d3a6490b642b755da2c6af7cb3e866ef8f8',
  ci: false,
  durationMs: 4916 }
2019-05-07T07:32:53.331Z snyk sending request to: https://snyk.io/api/v1/analytics/cli
2019-05-07T07:32:53.331Z snyk request body size: 2280
2019-05-07T07:32:53.331Z snyk gzipped request body size: 822
2019-05-07T07:32:53.331Z snyk not using proxy
```

**Comment by lili2311** [comment]
👋 @bertdida!
I was wondering if any of you had a chance to see a 🆕  feature we have in Beta called `snyk fix`? It is intended to be a new `wizard` version but with much wider support and *automatic* application of remediation (not a one by one manual process). 
The initial support if for **Pip**, **Poetry** & **Pipenv** projects to automatically test & apply remediation to your projects either by modifying the file or using the tooling if possible directly. We are looking for early beta feedback on this to see if this is a valuable feature & how it performs. Our current Github integration does not support all of these project types to fix via fix PRs so this is new & not something we had before. 

Please do check it out, try it and share with us any feedback you have on the provided email or otherwise so we can make this a great tool and release it to the general public 🙏 

https://support.snyk.io/hc/en-us/articles/4403417279505-Automatic-remediation-with-snyk-fix

**Comment by JackuB** [comment]
Closing as a stale issue. See https://docs.snyk.io for Snyk products documentation
Please reach out to https://support.snyk.io for Snyk product questions.
